# Generated by Django 3.1.2 on 2020-11-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
