apiVersion: apps/v1
kind: Deployment
metadata:
  name: sani-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: cannamaps-service
        image: mershab99/cannamaps-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
      - name: db
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: cannamaps_db
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: pass
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: mongodb-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: cannamaps-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
