apiVersion: v1
kind: Pod
metadata:
  name: expense-logger
  labels:
    app: web
spec:
  containers:
    - name: db
      image: postgres
      env:
      - name: POSTGRES_DB
        value: learning_db
      - name: POSTGRES_USER
        value: admin
      - name: POSTGRES_PASSWORD
        value: pass
      ports:
        - containerPort: 5432
    - name: api
      image: mershab99/expense-logger
      ports:
        - containerPort: 8000
      command: ["python"]
      args: ["learningProj/manage.py", "runserver", "0.0.0.0:8000"]
