version: "3.8"

services: 
    web:
        build: .
        command: python mysite/manage.py runserver 0:8000
        container_name: django-test
        volumes:
            - .:/code
        ports:
            - "8000:8000"