version: "3.8"

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment: 
            - POSTGRES_DB=learning_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=pass
    web:
        build: .
        command: python learningProj/manage.py runserver 0.0.0.0:8000
        image: mershab99/expense-logger
        tty: true
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db