version: '3.8'

services:
  minio:
    image: minio/minio
    volumes:
      - data-pit0/:/data
    environment:
      MINIO_ROOT_USER: learning
      MINIO_ROOT_PASSWORD: test123
    expose:
      - 9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
